volumes:
  production_traefik: {}
  production_redis_data: {}
  flower_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: luca_production_django
    depends_on:
      - redis
    env_file:
      - ./.envs/.production/.django
    command: /start
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: luca_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  redis:
    image: docker.io/redis:7
    volumes:
      - production_redis_data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  celeryworker:
    <<: *django
    image: luca_production_celeryworker
    command: /start-celeryworker
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  celerybeat:
    <<: *django
    image: luca_production_celerybeat
    command: /start-celerybeat
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  flower:
    <<: *django
    image: luca_production_flower
    command: /start-flower
    volumes:
      - flower_data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
